spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_IP:localhost}:3306/goserver?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ENC(NTYa4maTBpxzkV/dEAY9XA==)
    password: ENC(KRGubC5Bw6ItS00ZHFXgKtl2vWQecvTK7dCquwyAutI=)
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false
  application:
    name: go-platform-server
server:
  port: 8084
  forward-headers-strategy: framework
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
apiPrefix: /api # 所有 Controller 共同的前缀
app:
  version: @project.version@ # pom.xml 中定义的版本号
jwt:
  secret: ENC(N3fG/db7SlKPsmqxBnSbUwG65fF+dNsTFisJ8ikq4r+7Azjcozrt++HFhk1DOL0xwfIlHgN8p0tYoc7FkuKd/ROuhb4cuu1+dC81dHRApu9qCuoxrZ2YWHX06yVZLxLaSH1zf68Lbs4oyeE7/x2C5oR4HL5Nh8peUkdhqse7XXryFSQ6BmpDZ6jCwWYFfdZi)
logging:
  level:
    root: info
    com.goplatform.server: debug
katago:
  url: https://dragondj.space/
