spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_IP:localhost}:3306/goserver?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: ENC(NTYa4maTBpxzkV/dEAY9XA==)
    username: root
#    password: ENC(KRGubC5Bw6ItS00ZHFXgKtl2vWQecvTK7dCquwyAutI=)
    password: Admin12!
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: go-platform-server
server:
  port: 8084
  forward-headers-strategy: framework
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
