spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goserver?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Admin12!
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: go-platform-server
server:
  port: 8084
